name: Java CI with Maven

on:
  push:
    branches: [ master, main, github-actions-migration ]
  pull_request:
    branches: [ master, main, github-actions-migration ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Archive Test Reports
      if: always()
      uses: actions/upload-artifact@v2.3.0   # <-- fixed to a specific version
      with:
        name: junit-test-results
        path: target/surefire-reports/
